import { StyleSheet } from 'react-native';
export const palette = { ink: '#172B40', muted: '#536778', primary: '#194F85', canvas: '#F5F7FA', line: '#D6DFE8', paper: '#FFFFFF', danger: '#A11D27' };
export const expenseStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: palette.canvas },
  content: { width: '100%', maxWidth: 680, alignSelf: 'center', padding: 20, gap: 20, paddingBottom: 40 },
  title: { fontSize: 26, fontWeight: '700', color: palette.ink },
  heading: { fontSize: 19, fontWeight: '700', color: palette.ink },
  text: { fontSize: 16, color: palette.ink, lineHeight: 24 },
  muted: { fontSize: 14, color: palette.muted, lineHeight: 22 },
  eyebrow: { fontSize: 12, fontWeight: '700', letterSpacing: 1, color: palette.primary },
  field: { gap: 8 },
  row: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 10 },
  input: { borderWidth: 1, borderColor: '#778A9C', borderRadius: 10, minHeight: 48, paddingHorizontal: 14, paddingVertical: 12, color: palette.ink, fontSize: 16, backgroundColor: palette.paper },
  selectionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  selectionButton: { flexGrow: 1, borderWidth: 1, borderColor: '#778A9C', borderRadius: 10, minHeight: 48, paddingHorizontal: 14, justifyContent: 'center', backgroundColor: palette.paper },
  selectionText: { color: palette.ink, fontSize: 16 },
  nowButton: { minWidth: 64, minHeight: 48, borderRadius: 10, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E5EDF6' },
  nowText: { color: palette.primary, fontSize: 16, fontWeight: '600' },
  button: { minHeight: 48, backgroundColor: palette.primary, borderRadius: 12, padding: 14, alignItems: 'center', justifyContent: 'center' },
  voiceButton: { minHeight: 68 },
  buttonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
  secondary: { minHeight: 48, borderWidth: 1, borderColor: palette.line, borderRadius: 10, padding: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: palette.paper },
  secondaryText: { color: palette.primary, fontSize: 16, fontWeight: '600' },
  danger: { borderColor: '#DBA4AB', backgroundColor: '#FFF8F8' },
  dangerText: { color: palette.danger, fontSize: 16, fontWeight: '600' },
  disabled: { opacity: 0.5 },
  pressed: { opacity: 0.75 },
  error: { color: palette.danger, fontSize: 15, lineHeight: 23 },
  card: { backgroundColor: palette.paper, borderWidth: 1, borderColor: palette.line, borderRadius: 16, padding: 20, gap: 12 },
  softCard: { backgroundColor: palette.paper, borderWidth: 1, borderColor: '#E6ECF2', borderRadius: 24, padding: 24, gap: 12, boxShadow: '0px 4px 16px rgba(23, 43, 64, 0.06)' },
  review: { backgroundColor: '#EFF5FC', borderColor: '#93B2D1' },
  divider: { height: 1, backgroundColor: palette.line },
  amount: { fontSize: 34, fontWeight: '700', color: palette.ink, fontVariant: ['tabular-nums'] },
  record: { minHeight: 88, borderBottomWidth: 1, borderBottomColor: palette.line, paddingVertical: 16, gap: 4 },
  recordAmount: { fontSize: 21, fontWeight: '700', color: palette.ink, fontVariant: ['tabular-nums'] },
});
